// Package render resolves a service's config for one environment or sandbox:
// it merges the five layers, enforces the schema, resolves $output references,
// turns $secret and $kv references into ExternalSecret inputs, and produces
// the values file the central chart deploys from.
package render

import (
	"bytes"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"text/template"

	"github.com/mcafeelabs/platform/pkg/capabilities"
	"github.com/mcafeelabs/platform/pkg/manifest"
	"github.com/mcafeelabs/platform/pkg/refs"
	"github.com/mcafeelabs/platform/pkg/registry"
	"github.com/mcafeelabs/platform/pkg/values"
	"sigs.k8s.io/yaml"
)

// TopLevelKeys are the keys a layer may set. Anything else is a typo.
var TopLevelKeys = map[string]bool{"platform": true, "deployment": true, "image": true, "config": true}

// Target says what is being rendered: a long-lived environment, or a sandbox
// on top of its baseline environment.
type Target struct {
	Env     string
	Sandbox *registry.Sandbox
}

// Name returns "dev" or "sbx/<name>".
func (t Target) Name() string {
	if t.Sandbox != nil {
		return "sbx/" + t.Sandbox.Name
	}
	return t.Env
}

// Result is one rendered service.
type Result struct {
	Service string
	Target  Target
	// Values is the chart input.
	Values map[string]any
}

// Path returns where the values file is written, relative to the repo root.
func (r Result) Path() string {
	return "rendered/" + r.Target.Name() + "/" + r.Service + "/values.yaml"
}

// Header is written at the top of every generated file.
const Header = "# Generated by svcreg from the services repo. DO NOT EDIT.\n"

// YAML returns the values file content.
func (r Result) YAML() ([]byte, error) {
	b, err := yaml.Marshal(r.Values)
	if err != nil {
		return nil, err
	}
	return append([]byte(Header), b...), nil
}

// Renderer renders services from a loaded registry.
type Renderer struct {
	Reg   *registry.Registry
	waves map[string]int
}

// New returns a renderer. The registry should already be validated.
func New(reg *registry.Registry) (*Renderer, error) {
	w, err := reg.Graph().Waves()
	if err != nil {
		return nil, err
	}
	return &Renderer{Reg: reg, waves: w}, nil
}

// Errors from rendering one or more services.
type Errors []error

func (e Errors) Error() string {
	msgs := make([]string, len(e))
	for i, x := range e {
		msgs[i] = "  - " + x.Error()
	}
	return fmt.Sprintf("%d render problem(s):\n%s", len(e), strings.Join(msgs, "\n"))
}

// Env renders every service for a long-lived environment.
func (rd *Renderer) Env(env string) ([]Result, error) {
	if _, ok := rd.Reg.Envs[env]; !ok {
		return nil, fmt.Errorf("unknown environment %q", env)
	}
	var out []Result
	var errs Errors
	for _, svc := range rd.Reg.ServiceNames() {
		r, err := rd.Service(svc, Target{Env: env})
		if err != nil {
			errs = append(errs, err)
			continue
		}
		out = append(out, r)
	}
	if len(errs) > 0 {
		return out, errs
	}
	return out, nil
}

// Sandbox renders the services a sandbox runs.
func (rd *Renderer) Sandbox(name string) ([]Result, error) {
	sb, ok := rd.Reg.Sandboxes[name]
	if !ok {
		return nil, fmt.Errorf("unknown sandbox %q", name)
	}
	var out []Result
	var errs Errors
	for _, svc := range sb.ServiceNames() {
		r, err := rd.Service(svc, Target{Env: sb.Baseline, Sandbox: sb})
		if err != nil {
			errs = append(errs, err)
			continue
		}
		out = append(out, r)
	}
	if len(errs) > 0 {
		return out, errs
	}
	return out, nil
}

// Layers returns the merged, unresolved values for svc in target: global,
// environment, service, service x environment, then the sandbox's values.
func (rd *Renderer) Layers(svc string, t Target) (map[string]any, error) {
	s, ok := rd.Reg.Services[svc]
	if !ok {
		return nil, fmt.Errorf("unknown service %q", svc)
	}
	envLayer, ok := rd.Reg.Envs[t.Env]
	if !ok {
		return nil, fmt.Errorf("unknown environment %q", t.Env)
	}
	layers := []struct {
		name string
		v    map[string]any
	}{
		{"_global/values.yaml", rd.Reg.Global},
		{"environments/" + t.Env + "/values.yaml", envLayer},
		{"services/" + svc + "/values.yaml", s.Values},
		{"services/" + svc + "/environments/" + t.Env + "/values.yaml", s.EnvValues[t.Env]},
	}
	if t.Sandbox != nil {
		ss, _ := t.Sandbox.Service(svc)
		layers = append(layers, struct {
			name string
			v    map[string]any
		}{"sandboxes/" + t.Sandbox.Name + ".yaml values", ss.Values})
	}
	merged := map[string]any{}
	for _, l := range layers {
		for k := range l.v {
			if !TopLevelKeys[k] {
				return nil, fmt.Errorf("%s: unknown top-level key %q (allowed: config, deployment, image, platform)", l.name, k)
			}
		}
		merged = values.Merge(merged, l.v)
	}
	return merged, nil
}

// Scope identifies where a service's resources live.
type Scope struct {
	Env       string
	Namespace string
	// Sandbox is empty for the long-lived environment.
	Sandbox string
}

// prefix names resources: dev, or dev-sbx-<name>.
func (s Scope) prefix() string {
	if s.Sandbox != "" {
		return s.Env + "-sbx-" + s.Sandbox
	}
	return s.Env
}

// OutputKey is the outputs-store path of a dynamic output.
func (s Scope) OutputKey(svc, output string) string {
	if s.Sandbox != "" {
		return "sandboxes/" + s.Sandbox + "/" + svc + "/" + output
	}
	return "services/" + s.Env + "/" + svc + "/" + output
}

// scopes returns the baseline scope and, in a sandbox, the sandbox scope.
func (rd *Renderer) scopes(merged map[string]any, t Target) (baseline, own Scope) {
	ns := values.GetString(merged, "platform", "namespace")
	if ns == "" {
		ns = t.Env
	}
	baseline = Scope{Env: t.Env, Namespace: ns}
	own = baseline
	if t.Sandbox != nil {
		own = Scope{Env: t.Env, Namespace: "sbx-" + t.Sandbox.Name, Sandbox: t.Sandbox.Name}
	}
	return baseline, own
}

// outputScope picks where svc's output resolves from the point of view of
// target: the sandbox's copy if the sandbox runs svc and the output is
// isolated, otherwise the baseline.
func (rd *Renderer) outputScope(svc string, out manifest.Output, t Target, baseline, own Scope) Scope {
	if t.Sandbox != nil && t.Sandbox.Overrides(svc) && out.SandboxMode(rd.Reg.Caps) == manifest.SandboxIsolate {
		return own
	}
	return baseline
}

var dnsUnsafe = regexp.MustCompile(`[^a-z0-9-]+`)

// ResourceName turns <svc>-<output> into a DNS label.
func ResourceName(svc, output string) string {
	n := dnsUnsafe.ReplaceAllString(strings.ToLower(svc+"-"+output), "-")
	if len(n) > 52 {
		n = n[:52]
	}
	return strings.Trim(n, "-")
}

func deterministicValue(k capabilities.Kind, sc Scope, svc, output string) (string, error) {
	tpl, err := template.New("value").Option("missingkey=error").Parse(k.Value)
	if err != nil {
		return "", err
	}
	var b bytes.Buffer
	err = tpl.Execute(&b, map[string]string{
		"Env": sc.prefix(), "Environment": sc.Env, "Service": svc, "Output": dnsUnsafe.ReplaceAllString(output, "-"),
		"Name": output, "Namespace": sc.Namespace, "Sandbox": sc.Sandbox,
	})
	return b.String(), err
}

// store is an environment's mapping of a provider name to a secret store.
type store struct {
	Name     string `json:"name"`
	Kind     string `json:"kind"`
	KeyStyle string `json:"keyStyle"`
}

func stores(merged map[string]any) (map[string]store, error) {
	raw := values.GetMap(merged, "platform", "secretStores")
	out := map[string]store{}
	for provider, v := range raw {
		b, _ := yaml.Marshal(v)
		var s store
		if err := yaml.UnmarshalStrict(b, &s); err != nil {
			return nil, fmt.Errorf("platform.secretStores.%s: %w", provider, err)
		}
		if s.Name == "" {
			return nil, fmt.Errorf("platform.secretStores.%s.name is required", provider)
		}
		if s.Kind == "" {
			s.Kind = "ClusterSecretStore"
		}
		switch s.KeyStyle {
		case "":
			s.KeyStyle = "path"
		case "path", "dotted":
		default:
			return nil, fmt.Errorf("platform.secretStores.%s.keyStyle must be path or dotted", provider)
		}
		out[provider] = s
	}
	return out, nil
}

// remote maps a provider key and property to what the store expects. AWS
// stores take /path keys; the Kubernetes provider used in localdev takes a
// Secret name, so dotted style turns orders/db into orders.db and defaults the
// property to "value".
func (s store) remote(key, property string) (string, string) {
	if s.KeyStyle == "dotted" {
		if property == "" {
			property = "value"
		}
		return strings.ReplaceAll(strings.Trim(key, "/"), "/", "."), property
	}
	return "/" + strings.Trim(key, "/"), property
}

// Service renders one service.
func (rd *Renderer) Service(svc string, t Target) (Result, error) {
	res, err := rd.service(svc, t)
	if err != nil {
		return Result{}, fmt.Errorf("%s/%s: %w", t.Name(), svc, err)
	}
	return res, nil
}

func (rd *Renderer) service(svc string, t Target) (Result, error) {
	s := rd.Reg.Services[svc]
	if s == nil {
		return Result{}, fmt.Errorf("unknown service %q", svc)
	}
	m := s.Manifest
	merged, err := rd.Layers(svc, t)
	if err != nil {
		return Result{}, err
	}
	baseline, own := rd.scopes(merged, t)
	var errs Errors

	config := values.GetMap(merged, "config")
	if s.Schema != nil {
		errs = append(errs, s.Schema.CheckRefs(config)...)
	}

	consumes := map[string]bool{}
	for _, c := range m.Consumes {
		consumes[c.Service+"/"+c.Output] = true
	}
	outputsProvider := values.GetString(merged, "platform", "outputs", "provider")

	// Resolve $output: deterministic outputs become literals, dynamic ones a
	// $kv reference to the outputs store.
	resolved, err := refs.Replace(config, func(path []string, r refs.Ref) (any, error) {
		if r.Kind != refs.Output {
			return r.Map(), nil
		}
		at := "config." + refs.PathString(path)
		target, ok := rd.Reg.Services[r.Service]
		if !ok {
			return nil, fmt.Errorf("%s: $output %s: service %q does not exist", at, r.Raw, r.Service)
		}
		out, ok := target.Manifest.Output(r.Output)
		if !ok {
			return nil, fmt.Errorf("%s: $output %s: %s does not provide %q", at, r.Raw, r.Service, r.Output)
		}
		if r.Service != svc && !consumes[r.Service+"/"+r.Output] {
			return nil, fmt.Errorf("%s: $output %s: add {service: %s, output: %s} to consumes in service.yaml", at, r.Raw, r.Service, r.Output)
		}
		kind := rd.Reg.Caps.Kinds[out.Kind]
		sc := rd.outputScope(r.Service, out, t, baseline, own)
		switch kind.Output {
		case capabilities.Deterministic:
			if r.Property != "" {
				return nil, fmt.Errorf("%s: $output %s: %s outputs have no properties", at, r.Raw, out.Kind)
			}
			return deterministicValue(kind, sc, r.Service, r.Output)
		default:
			if r.Property == "" || !containsStr(kind.Keys, r.Property) {
				return nil, fmt.Errorf("%s: $output %s: pick a key with #<key> (one of %s)", at, r.Raw, strings.Join(kind.Keys, ", "))
			}
			if outputsProvider == "" {
				return nil, fmt.Errorf("%s: $output %s: platform.outputs.provider is not set for %s", at, r.Raw, t.Env)
			}
			return map[string]any{"$kv": outputsProvider + "://" + sc.OutputKey(r.Service, r.Output) + "#" + r.Property}, nil
		}
	})
	if err != nil {
		errs = append(errs, err)
		return Result{}, errs
	}
	resolvedConfig := resolved.(map[string]any)

	if s.Schema != nil {
		errs = append(errs, s.Schema.Validate(resolvedConfig)...)
	}

	storeMap, err := stores(merged)
	if err != nil {
		errs = append(errs, err)
	}
	configFile, err := buildConfigFile(resolvedConfig, storeMap)
	if err != nil {
		errs = append(errs, err)
	}

	outputs, err := rd.outputs(m, t, own, storeMap, outputsProvider)
	if err != nil {
		errs = append(errs, err)
	}

	image, err := rd.image(svc, merged, t)
	if err != nil {
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return Result{}, errs
	}

	sbx := map[string]any{"name": "", "baselineNamespace": ""}
	if t.Sandbox != nil {
		sbx = map[string]any{"name": t.Sandbox.Name, "baselineNamespace": baseline.Namespace}
	}
	vals := map[string]any{
		"service": map[string]any{
			"name":        svc,
			"owner":       m.Owner,
			"profile":     m.ChartProfile,
			"environment": t.Env,
			"namespace":   own.Namespace,
			"wave":        rd.waves[svc],
			"sandbox":     sbx,
		},
		"image":      image,
		"platform":   values.GetMap(merged, "platform"),
		"deployment": values.GetMap(merged, "deployment"),
		"outputs":    outputs,
		"config":     resolvedConfig,
		"configFile": configFile,
	}
	return Result{Service: svc, Target: t, Values: vals}, nil
}

func containsStr(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}

// outputs lists what the service provides, with the names and publishing
// details the chart needs to provision them. In a sandbox only isolated
// outputs are provisioned; shared ones stay with the baseline.
func (rd *Renderer) outputs(m *manifest.Manifest, t Target, own Scope, storeMap map[string]store, provider string) ([]any, error) {
	out := []any{}
	for _, o := range m.Provides {
		kind := rd.Reg.Caps.Kinds[o.Kind]
		mode := o.SandboxMode(rd.Reg.Caps)
		provision := t.Sandbox == nil || mode == manifest.SandboxIsolate
		entry := map[string]any{
			"name":         o.Name,
			"kind":         o.Kind,
			"sandbox":      mode,
			"provision":    provision,
			"resourceName": ResourceName(m.Name, o.Name),
		}
		if kind.Output == capabilities.Deterministic {
			v, err := deterministicValue(kind, own, m.Name, o.Name)
			if err != nil {
				return nil, err
			}
			entry["value"] = v
		} else {
			entry["connectionSecret"] = ResourceName(m.Name, o.Name) + "-conn"
			st, ok := storeMap[provider]
			if !ok {
				return nil, fmt.Errorf("provides %s: outputs provider %q has no entry in platform.secretStores", o.Name, provider)
			}
			var keys []any
			for _, k := range kind.Keys {
				rk, rp := st.remote(own.OutputKey(m.Name, o.Name), k)
				keys = append(keys, map[string]any{"secretKey": k, "remoteKey": rk, "property": rp})
			}
			entry["publish"] = map[string]any{
				"store": map[string]any{"name": st.Name, "kind": st.Kind},
				"keys":  keys,
			}
		}
		out = append(out, entry)
	}
	return out, nil
}

// image resolves repository and tag. A sandbox entry's image (name:tag or
// repo/name:tag) overrides the layers.
func (rd *Renderer) image(svc string, merged map[string]any, t Target) (map[string]any, error) {
	img := values.DeepCopy(values.GetMap(merged, "image")).(map[string]any)
	if _, ok := img["repository"]; !ok {
		img["repository"] = strings.TrimSuffix(rd.Reg.Config.Images.Registry, "/") + "/" + svc
	}
	if t.Sandbox != nil {
		if ss, _ := t.Sandbox.Service(svc); ss.Image != "" {
			i := strings.LastIndex(ss.Image, ":")
			if i <= 0 || strings.Contains(ss.Image[i:], "/") {
				return nil, fmt.Errorf("sandbox image %q must be name:tag", ss.Image)
			}
			name, tag := ss.Image[:i], ss.Image[i+1:]
			if !strings.Contains(name, "/") {
				name = strings.TrimSuffix(rd.Reg.Config.Images.Registry, "/") + "/" + name
			}
			img["repository"], img["tag"] = name, tag
		}
	}
	if tag, _ := img["tag"].(string); tag == "" {
		return nil, errors.New("image.tag is not set by any layer")
	}
	return img, nil
}

// buildConfigFile produces the config.yaml template and the references the
// chart turns into one ExternalSecret. Without references the template is
// the literal config.
func buildConfigFile(config map[string]any, storeMap map[string]store) (map[string]any, error) {
	var refList []any
	var errs Errors
	n := 0
	sentinel := func(i int) string { return fmt.Sprintf("__SVCREG_REF_%d__", i) }
	withSentinels, err := refs.Replace(config, func(path []string, r refs.Ref) (any, error) {
		st, ok := storeMap[r.Provider]
		if !ok {
			errs = append(errs, fmt.Errorf("config.%s: provider %q has no entry in platform.secretStores", refs.PathString(path), r.Provider))
			return "", nil
		}
		key, prop := st.remote(r.Key, r.Property)
		id := fmt.Sprintf("ref%d", n)
		ref := map[string]any{
			"id":    id,
			"path":  refs.PathString(path),
			"kind":  string(r.Kind),
			"store": map[string]any{"name": st.Name, "kind": st.Kind},
			"key":   key,
		}
		if prop != "" {
			ref["property"] = prop
		}
		refList = append(refList, ref)
		s := sentinel(n)
		n++
		return s, nil
	})
	if err != nil {
		return nil, err
	}
	if len(errs) > 0 {
		return nil, errs
	}
	b, err := yaml.Marshal(withSentinels)
	if err != nil {
		return nil, err
	}
	tpl := string(b)
	if n > 0 {
		// ESO renders the template with Go templates: escape literal braces,
		// then swap each sentinel for its JSON-encoded secret value (valid YAML).
		tpl = strings.ReplaceAll(tpl, "{{", `{{ "{{" }}`)
		for i := 0; i < n; i++ {
			tpl = regexp.MustCompile(`["']?`+sentinel(i)+`["']?`).ReplaceAllString(tpl, fmt.Sprintf("{{ .ref%d | toJson }}", i))
		}
	}
	if refList == nil {
		refList = []any{}
	}
	return map[string]any{"template": tpl, "refs": refList}, nil
}
